### ISSUE TITLE
how use it this proxy in GitHub Desktop.

### ISSUE THREAD

**Issue by neozhu** [Cnily03/cf-worker-mirror#1]
I have deployed to CF workers and it's working.
![image](https://github.com/user-attachments/assets/285a25d7-e631-4e76-b7d3-ab69755d8325)
then how to use this proxy?
```c#
[https]
	proxy = https://mirrors.xxx.workers.dev:443
```

**Comment by Cnily03** [comment]
`https://mirrors.xxx.com/<url>` proxies `<url>`

The proxy also fits UserAgent automatically. You can just set docker mirrors to `https://mirrors.xxx.com` (only in docker UserAgent) or `https://mirrors.xxx.com/docker` (in any case).
If the UserAgent is git, the protocol like `https://` can be ignored in `<url>` area.

Examples:
```
git clone https://mirrors.xxx.com/example.com/some.git
curl https://mirrors.xxx.com/https://example.com/some.pdf
docker pull mirrors.xxx.com/oven/bun:latest
```
